#!/bin/bash

# Prints a message regarding how to use the program
usage() {
    echo "Usage: $0 -f <file> [-s <size>] [-t <tolerance>]"
    echo "  -f <file>        File to crush"
    echo "  -s <size>        Target size in MiB (default: 10)"
    echo "  -t <tolerance>   Tolerance in % (default: 5)"
    echo "  -o <output file> Name for output filename (default: <file>.crushed.<file type>)"
    echo "  -h               Display this help message"
}

# Should parse arguments. If no flags are given, display usage and exit with code 1
# Refer to above for flag definitions
while getopts f:s:t:o:h flag
do
    case "${flag}" in
        f) file=${OPTARG};;
        s) size=${OPTARG};;
        t) tolerance=${OPTARG};;
        o) output=${OPTARG};; 
        h) usage 
           exit 0;;
        *) echo ""
           usage
           exit 1;;
    esac
done

# Should exit unsuccessfully if no file has been provided, and program hasn't already exited
if [ -z "$file" ]; then
    usage
    exit 1
fi

# File, size, and tolerance are all passed from the command as args
python /usr/bin/8mb.py --file "$file" --size "${size:-10}" --tolerance "${tolerance:-5}" --output "${output:""}"