#!/bin/bash
sudo printf ""

if [[ $? ]] ;
then
    answers=("y" "yes" "Y" "Yes" "YES")

    read -r -p "Are you sure you want to uninstall? [y/N] " choice

    for option in "${answers[@]}" ;
    do
        if [[ $option == "$choice" ]] ;
        then            
            printf "\n\nRemoving videoCRUSHER script from from %s/.local/bin/" "$HOME"
            sudo rm "$HOME/.local/bin/videoCRUSHER" &> /dev/null
            printf "\nDone!"

            printf "\n\nRemoving videoCRUSHER.py program from %s/.local/" "$HOME"
            sudo rm "$HOME/.local/videoCRUSHER.py" &> /dev/null
            printf "\nDone!"

            printf "\n\nUninstalled!"

        fi
    done
fi
