#!/bin/bash
sudo printf ""

if [[ $? ]] ;
then
    answers=("y" "yes" "Y" "Yes" "YES")

    read -r -p "Are you sure you want to uninstall? [y/N] " choice

    for option in "${answers[@]}" ;
    do
        if [[ $option == "$choice" ]] ;
        then            
            printf "\n\nRemoving videoCRUSHER script from /usr/local/bin/videoCRUSHER"
            sudo rm /usr/local/bin/videoCRUSHER &> /dev/null
            printf "\nDone!"

            printf "\n\nRemoving videoCRUSHER script from /usr/bin/videoCRUSHER.py"
            sudo rm /usr/local/bin/videoCRUSHER &> /dev/null
            printf "\nDone!"

            printf "\n\nUninstalled!"

        fi
    done
fi
